version: '3'
services:
  # PostgreSQL database service
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - app-network

  # Diesel migration service
  diesel-migrate:
    build:
      context: ./db # Use the directory containing your Dockerfile
      dockerfile: Dockerfile.diesel
    depends_on:
      - database
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
    networks:
      - app-network

networks:
  app-network: