version: "3.7"

x-app: &django-app
  build:
    context: .
    dockerfile: django.Dockerfile
  volumes:
    - ./app:/app
  depends_on:
    - database
  networks:
    - app-network
  environment:
    DEBUG: ${DEBUG}
    DJANGO_SQL_ENGINE: ${DJANGO_SQL_ENGINE}
    DJANGO_SQL_DATABASE: ${DJANGO_SQL_DATABASE}
    DJANGO_SQL_USER: ${DJANGO_SQL_USER}
    DJANGO_SQL_PASSWORD: ${DJANGO_SQL_PASSWORD}
    DJANGO_SQL_HOST: ${DJANGO_SQL_HOST}
    DJANGO_SQL_PORT: ${DJANGO_SQL_PORT}
    SECRET_KEY: ${SECRET_KEY}
    DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
    DJANGO_HOST: ${DJANGO_HOST}
    DJANGO_CSRF_TRUSTED_ORIGINS: ${DJANGO_CSRF_TRUSTED_ORIGINS}
  restart: "unless-stopped"

services:
  traefik:
    image: traefik:v2.4
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    networks:
      - app-network
    depends_on:
      - web
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app/staticfiles:/usr/share/nginx/html/static:ro
      - ./app/media:/usr/share/nginx/html/media:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=(Host(`${DJANGO_HOST}`) && PathPrefix(`/static`)) || (Host(`${DJANGO_HOST}`) && PathPrefix(`/media`))"
      - "traefik.http.routers.nginx.entrypoints=websecure"
      - "traefik.http.routers.nginx.tls.certresolver=myresolver"
      - "traefik.docker.network=app-network"
    networks:
      - app-network
    environment:
      DJANGO_HOST: ${DJANGO_HOST}
    depends_on:
      - web
  database:
    image: postgres:14
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
  web:
    <<: *django-app
    command: "poetry run gunicorn app.wsgi:application --bind 0.0.0.0:8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=Host(`${DJANGO_HOST}`)"
      - "traefik.http.routers.django.entrypoints=websecure"
      - "traefik.http.routers.django.tls.certresolver=myresolver"
      - "traefik.docker.network=app-network"
    expose:
      - "8000"
    volumes:
      - "./app/staticfiles:/app/staticfiles"
      - "./app/media:/app/media"
  memcache:
    image: memcached:alpine
    ports:
      - "11211:11211"
    networks:
      - app-network

networks:
  app-network: