version: "3"

x-app: &django-app
  build:
    context: .
    dockerfile: django.Dockerfile
  volumes:
    - ./app:/app
  depends_on:
    - database
  networks:
    - app-network
  restart: "unless-stopped"

services:
  # PostgreSQL database service
  database:
    container_name: ${DB_SERVICE_NAME}
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - app-network
  # Django service with poetry
  web:
    <<: *django-app
    command: "poetry run python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      DEBUG: ${DEBUG}
      SQL_ENGINE: ${SQL_ENGINE}
      SQL_DATABASE: ${SQL_DATABASE}
      SQL_USER: ${SQL_USER}
      SQL_PASSWORD: ${SQL_PASSWORD}
      SQL_HOST: ${SQL_HOST}
      SQL_PORT: ${SQL_PORT}
      SECRET_KEY: ${SECRET_KEY}
  tailwind:
    <<: *django-app
    command: "poetry run python manage.py tailwind start"
    tty: true
networks:
  app-network: