version: "3"

x-app: &django-app
  build:
    context: .
    dockerfile: django.Dockerfile
  volumes:
    - ./app:/app
  depends_on:
    - database
  networks:
    - app-network
  restart: "unless-stopped"

services:
  # PostgreSQL database service
  database:
    image: postgres:14
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - app-network
  # Django service with poetry
  web:
    <<: *django-app
    command: "poetry run python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      DEBUG: ${DEBUG}
      DJANGO_SQL_ENGINE: ${DJANGO_SQL_ENGINE}
      DJANGO_SQL_DATABASE: ${DJANGO_SQL_DATABASE}
      DJANGO_SQL_USER: ${DJANGO_SQL_USER}
      DJANGO_SQL_PASSWORD: ${DJANGO_SQL_PASSWORD}
      DJANGO_SQL_HOST: database
      DJANGO_SQL_PORT: ${DJANGO_SQL_PORT}
      SECRET_KEY: ${SECRET_KEY}
  tailwind:
    <<: *django-app
    command: "poetry run python manage.py tailwind start"
    tty: true
networks:
  app-network: